language: php

matrix:
  include:
    - php: 5.5
      env:
        - DEPENDENCIES="--prefer-stable"
    - php: 5.5
      env:
        - DEPENDENCIES="--prefer-lowest --prefer-stable"
    - php: 5.6
      env:
        - DEPENDENCIES="--prefer-stable"
    - php: 5.6
      env:
        - DEPENDENCIES="--prefer-lowest --prefer-stable"
    - php: 7.0
      env:
        - DEPENDENCIES="--prefer-stable"
    - php: 7.0
      env:
        - DEPENDENCIES="--prefer-lowest --prefer-stable"
    - php: 7.1
      env:
        - DEPENDENCIES="--prefer-stable"
    - php: 7.1
      env:
        - DEPENDENCIES="--prefer-lowest --prefer-stable"


before_script:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer update --prefer-source $DEPENDENCIES

script:
  - phpunit --configuration tests/phpunit.xml
